[package]
name = "tesseract"
version = "0.1.1"
authors = ["Kevin Kwok <antimatter15@gmail.com>"]
description = """
Higher-level bindings for Tesseract OCR
"""
license = "MIT"

[dependencies]
libc = "0.1"

[dependencies.tesseract-sys]
version = "0.1.1"
path = "tesseract-sys"
